version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: api:${API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      API_HOST: 0.0.0.0
      API_DB_HOST: api-db
      API_DB_PORT: 3306
      API_DB_USER: api
      API_DB_PASS: api
      API_DB_BASE: api

  db:
    image: bitnami/mysql:8.0.30
    hostname: api-db
    restart: always
    environment:
      MYSQL_ROOT_USER: "api"
      MYSQL_ROOT_PASSWORD: "api"
      MYSQL_DATABASE: "api"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
    - api-db-data:/bitnami/mysql/data

  migrator:
    image: api:${API_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      API_DB_HOST: api-db
      API_DB_PORT: 3306
      API_DB_USER: api
      API_DB_PASS: api
      API_DB_BASE: api
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "api-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  api-db-data:
    name: api-db-data
